# Generated by Django 4.0 on 2022-05-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todoitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="status",
        ),
    ]
