# Generated by Django 4.0 on 2022-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_remove_todoitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="content",
            field=models.CharField(max_length=100),
        ),
    ]
